# Generated by Django 2.0.1 on 2018-01-19 03:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='评论内容')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '电影评论',
                'verbose_name_plural': '电影评论',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='电影名')),
                ('url', models.URLField(max_length=255, unique=True, verbose_name='播放地址')),
                ('info', models.TextField(max_length=500, verbose_name='电影简介')),
                ('logo', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='电影图')),
                ('star', models.SmallIntegerField(max_length=10, verbose_name='电影评星')),
                ('play_num', models.BigIntegerField(verbose_name='播放次数')),
                ('comment_num', models.BigIntegerField(verbose_name='评论次数')),
                ('area', models.CharField(max_length=50, verbose_name='上映地区')),
                ('release_time', models.DateField(verbose_name='上映日期')),
                ('length', models.CharField(max_length=100, verbose_name='电影长度')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '电影模型',
                'verbose_name_plural': '电影模型',
            },
        ),
        migrations.CreateModel(
            name='MovieLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.users.Movie', verbose_name='所属电影')),
            ],
            options={
                'verbose_name': '电影收藏',
                'verbose_name_plural': '电影收藏',
            },
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('logo', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='预告图')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '上映预告',
                'verbose_name_plural': '上映预告',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '电影标签',
                'verbose_name_plural': '电影标签',
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='ip地址')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '会员登录日志',
                'verbose_name_plural': '会员登录日志',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True, verbose_name='昵称')),
                ('pwd', models.CharField(max_length=50, verbose_name='密码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('info', models.TextField(max_length=255)),
                ('face', models.ImageField(default='image/default.png', upload_to='image/%Y/%m')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
                ('uuid', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.AddField(
            model_name='userlog',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.users.UserProfile', verbose_name='所属会员'),
        ),
        migrations.AddField(
            model_name='movielike',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.users.UserProfile', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.users.Tag', verbose_name='电影所属标签'),
        ),
        migrations.AddField(
            model_name='comment',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.users.Movie', verbose_name='所属电影'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.users.UserProfile', verbose_name='所属用户'),
        ),
    ]
