# Generated by Django 2.0.1 on 2018-01-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='star',
            field=models.SmallIntegerField(verbose_name='电影评星'),
        ),
    ]
