# Generated by Django 2.0.1 on 2018-05-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180510_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sign',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='个签'),
        ),
    ]
