# Generated by Django 2.0.1 on 2018-05-03 13:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='评论内容')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '电影评论',
                'verbose_name_plural': '电影评论',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(blank=True, max_length=260, null=True, verbose_name='译名')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='片名')),
                ('year', models.CharField(blank=True, max_length=60, null=True, verbose_name='上映年份')),
                ('country', models.CharField(blank=True, max_length=64, null=True, verbose_name='产地|国家')),
                ('category', models.CharField(blank=True, max_length=128, null=True, verbose_name='标签')),
                ('language', models.CharField(blank=True, max_length=64, null=True, verbose_name='电影语言')),
                ('subtitle', models.CharField(blank=True, max_length=64, null=True, verbose_name='字幕语言')),
                ('release_time', models.CharField(blank=True, max_length=64, null=True, verbose_name='上映时间')),
                ('score', models.CharField(blank=True, max_length=256, null=True, verbose_name='评分')),
                ('file_count', models.CharField(blank=True, max_length=128, null=True, verbose_name='计数')),
                ('duration', models.CharField(blank=True, max_length=128, null=True, verbose_name='片长')),
                ('director', models.CharField(blank=True, max_length=128, null=True, verbose_name='导演')),
                ('download_url', models.TextField(max_length=500, verbose_name='下载地址')),
            ],
            options={
                'verbose_name': '电影模型',
                'verbose_name_plural': '电影模型',
            },
        ),
        migrations.CreateModel(
            name='MovieLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Movie', verbose_name='所属电影')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '电影收藏',
                'verbose_name_plural': '电影收藏',
            },
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('logo', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='预告图')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '上映预告',
                'verbose_name_plural': '上映预告',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='标签名')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '电影标签',
                'verbose_name_plural': '电影标签',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Movie', verbose_name='所属电影'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
