# Generated by Django 2.0.1 on 2018-05-24 20:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='评论内容')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '电影评论',
                'verbose_name_plural': '电影评论',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='电影语言名')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '电影语言',
                'verbose_name_plural': '电影语言',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260, verbose_name='片名')),
                ('year', models.CharField(max_length=60, verbose_name='上映年份')),
                ('name_other', models.CharField(blank=True, max_length=128, null=True, verbose_name='别名')),
                ('director', models.CharField(default='', max_length=128, verbose_name='导演')),
                ('actor', models.CharField(default='', max_length=280, verbose_name='主演')),
                ('image', models.ImageField(default='movie/default.png', upload_to='movie/%Y/%m', verbose_name='电影图')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='上映时间')),
                ('intro', models.TextField(default='', max_length=500, verbose_name='电影介绍')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('duration', models.CharField(max_length=128, verbose_name='片长')),
                ('score_douban', models.FloatField(blank=True, null=True, verbose_name='豆瓣评分')),
                ('score_imdb', models.FloatField(blank=True, null=True, verbose_name='IMDB评分')),
                ('douban_url', models.TextField(default='', max_length=500, verbose_name='豆瓣电影链接地址')),
                ('imdb_url', models.TextField(default='', max_length=500, verbose_name='IMDB链接地址')),
                ('download_url', models.TextField(default='', max_length=500, verbose_name='下载地址')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
                ('languages', models.ManyToManyField(to='films.Language', verbose_name='语言')),
            ],
            options={
                'verbose_name': '电影模型',
                'verbose_name_plural': '电影模型',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='地区名')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '产地',
                'verbose_name_plural': '产地',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='标签名')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '电影标签',
                'verbose_name_plural': '电影标签',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Region', verbose_name='产地'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(to='films.Tag', verbose_name='电影类型'),
        ),
        migrations.AddField(
            model_name='comment',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Movie', verbose_name='所属电影'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
