# Generated by Django 2.0.1 on 2018-01-20 11:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='评论内容')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '电影评论',
                'verbose_name_plural': '电影评论',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='电影名')),
                ('url', models.URLField(max_length=255, unique=True, verbose_name='播放地址')),
                ('info', models.TextField(max_length=500, verbose_name='电影简介')),
                ('logo', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='电影图')),
                ('star', models.SmallIntegerField(verbose_name='电影评星')),
                ('play_num', models.BigIntegerField(verbose_name='播放次数')),
                ('comment_num', models.BigIntegerField(verbose_name='评论次数')),
                ('area', models.CharField(max_length=50, verbose_name='上映地区')),
                ('release_time', models.DateField(verbose_name='上映日期')),
                ('length', models.CharField(max_length=100, verbose_name='电影长度')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '电影模型',
                'verbose_name_plural': '电影模型',
            },
        ),
        migrations.CreateModel(
            name='MovieLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Movie', verbose_name='所属电影')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '电影收藏',
                'verbose_name_plural': '电影收藏',
            },
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('logo', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='预告图')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '上映预告',
                'verbose_name_plural': '上映预告',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '电影标签',
                'verbose_name_plural': '电影标签',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Tag', verbose_name='电影所属标签'),
        ),
        migrations.AddField(
            model_name='comment',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Movie', verbose_name='所属电影'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='所属用户'),
        ),
    ]
