# Generated by Django 2.0.1 on 2018-05-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_time',
            new_name='release_date',
        ),
    ]
