# Generated by Django 2.0.1 on 2018-05-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='movie/default.png', null=True, upload_to='movie/%Y/%m', verbose_name='电影图'),
        ),
    ]
