# Generated by Django 2.0.1 on 2018-05-10 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20180503_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='地区名')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '上映地区',
                'verbose_name_plural': '上映地区',
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='file_count',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='name_cn',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='score',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.CharField(default='', max_length=280, verbose_name='主演'),
        ),
        migrations.AddField(
            model_name='movie',
            name='add_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='movie',
            name='douban_url',
            field=models.TextField(default='', max_length=500, verbose_name='豆瓣电影链接地址'),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_url',
            field=models.TextField(default='', max_length=500, verbose_name='IMDB链接地址'),
        ),
        migrations.AddField(
            model_name='movie',
            name='name_other',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='别名'),
        ),
        migrations.AddField(
            model_name='movie',
            name='score_douban',
            field=models.IntegerField(blank=True, null=True, verbose_name='豆瓣评分'),
        ),
        migrations.AddField(
            model_name='movie',
            name='score_imdb',
            field=models.IntegerField(blank=True, null=True, verbose_name='IMDB评分'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(to='films.Tag', verbose_name='电影类型'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=128, verbose_name='导演'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='download_url',
            field=models.TextField(default='', max_length=500, verbose_name='下载地址'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=128, verbose_name='片长'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=64, verbose_name='电影语言'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=260, verbose_name='片名'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(verbose_name='上映时间'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(max_length=60, verbose_name='上映年份'),
        ),
        migrations.AddField(
            model_name='movie',
            name='regions',
            field=models.ManyToManyField(to='films.Region', verbose_name='上映地区|国家'),
        ),
    ]
