# Generated by Django 2.0.1 on 2018-05-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20180524_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='主演'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='download_url',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='下载地址'),
        ),
    ]
