# Generated by Django 2.0.1 on 2018-05-10 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20180510_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='电影语言名')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '电影语言',
                'verbose_name_plural': '电影语言',
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='image/movie/default.png', upload_to='image/%Y/%m', verbose_name='预告图'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=128, verbose_name='导演'),
        ),
        migrations.AddField(
            model_name='movie',
            name='languages',
            field=models.ManyToManyField(to='films.Language', verbose_name='语言'),
        ),
    ]
