# Generated by Django 2.0.1 on 2018-05-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20180510_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='image/movie/default.png', upload_to='image/%Y/%m', verbose_name='电影图'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score_douban',
            field=models.FloatField(blank=True, null=True, verbose_name='豆瓣评分'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score_imdb',
            field=models.FloatField(blank=True, null=True, verbose_name='IMDB评分'),
        ),
    ]
