# Generated by Django 2.0.1 on 2018-05-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_auto_20180510_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preview',
        ),
        migrations.AddField(
            model_name='movie',
            name='intro',
            field=models.TextField(default='', max_length=300, verbose_name='电影介绍'),
        ),
    ]
