# Generated by Django 2.0.1 on 2018-05-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_auto_20180510_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否热门'),
        ),
    ]
