# Generated by Django 2.0.1 on 2018-05-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_movie_is_hot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='movie/default.png', upload_to='movie/%Y/%m', verbose_name='电影图'),
        ),
    ]
