# Generated by Django 2.0.1 on 2018-05-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_auto_20180511_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='add_like',
            field=models.IntegerField(default=0, max_length=120, verbose_name='收藏数'),
        ),
    ]
