# Generated by Django 2.0.1 on 2018-05-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_movie_add_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielike',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='movielike',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='MovieLike',
        ),
    ]
